export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED';

export const DECK = {
  FETCH_SUCCESS: 'DECK_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_FETCH_ERROR',
};

export const CARD = {
  CARD_SUCCESS: 'CARD_FETCH_SUCCESS',
  CARD_ERROR: 'CARD_FETCH_ERROR',
};

export const GAME_STATE = {
  GUESS_EVEN: 'GUESS_EVEN',
  GUESS_ODD: 'GUESS_ODD',
  CORRECT_COUNT: 'CORRECT_GUESS_COUNT'
};
